blank_issues_enabled: true
contact_links:
  - name: Want to Discuss something?
    about: Join in our discord server.
    url: https://bit.ly/mclub-s4
  - name: Contributing Guidelines
    url: https://github.com/Microsoft-Club-SIST/mclub-website/blob/main/CONTRIBUTING.md
    about: Our contribution guidelines (Please go through them).